// -*- coding: utf-8 -*-
// Generated by scripts/generate_labels.py

export default {
    AUDIO_DESCRIPTION: "LNqKSN9j",
    ALT_TEXT: "Lb0tb9VC",
    CAPTIONS_SUBTITLES: "WnIhbgkY",
    HIGH_CONTRAST: "uF4CI2wP",
    TAGGED_PDF: "Kxx#meDW",
    SIGN_LANGUAGE: "Dr4cVXkc",
};
