// -*- coding: utf-8 -*-
// Generated by scripts/generate_labels.py

export default {
    AUDIO_DESCRIPTION: "cwDcsY",
    ALT_TEXT: "cuhrmh",
    CAPTIONS_SUBTITLES: "da2iCe",
    HIGH_CONTRAST: "br&HYl",
    TAGGED_PDF: "crDF4W",
    SIGN_LANGUAGE: "b1hGk&",
};
