// -*- coding: utf-8 -*-
// Generated by scripts/generate_from_specs.py

import AccessibilityCategories from "./AccessibilityCategories";
import LearningActivities from "./LearningActivities";
import Levels from "./Levels";
import Needs from "./Needs";
import ResourceType from "./ResourceType";
import Subjects from "./Subjects";

export default {
    AccessibilityCategories: AccessibilityCategories,
    LearningActivities: LearningActivities,
    Levels: Levels,
    Needs: Needs,
    ResourceType: ResourceType,
    Subjects: Subjects,
};
