// -*- coding: utf-8 -*-
// Generated by scripts/generate_labels.py

import Needs from "./Needs";
import AccessibilityCategories from "./AccessibilityCategories";
import ResourceType from "./ResourceType";
import Levels from "./Levels";
import Subjects from "./Subjects";
import LearningActivities from "./LearningActivities";

export default {
    Needs: Needs,
    AccessibilityCategories: AccessibilityCategories,
    ResourceType: ResourceType,
    Levels: Levels,
    Subjects: Subjects,
    LearningActivities: LearningActivities,
};
