// -*- coding: utf-8 -*-
// Generated by scripts/generate_from_specs.py

import Needs from "./Needs";
import AccessibilityCategories from "./AccessibilityCategories";
import ResourceType from "./ResourceType";
import Levels from "./Levels";
import LearningActivities from "./LearningActivities";
import Subjects from "./Subjects";

export default {
    Needs: Needs,
    AccessibilityCategories: AccessibilityCategories,
    ResourceType: ResourceType,
    Levels: Levels,
    LearningActivities: LearningActivities,
    Subjects: Subjects,
};
