// -*- coding: utf-8 -*-
// Generated by scripts/generate_labels.py

export default {
    READ: "wA01urpi",
    CREATE: "UXADWcXZ",
    PRACTICE: "VwRCom7G",
    WATCH: "UD5UGM0z",
    REFLECT: "3dSeJhqs",
    EXPLORE: "#j8L0eq3",
    LISTEN: "mkA1R3NU",
};
