// -*- coding: utf-8 -*-
// Generated by scripts/generate_labels.py

export default {
    READ: "bzRtvr",
    CREATE: "c7fP3a",
    PRACTICE: "c9ATW4",
    WATCH: "c53M6c",
    REFLECT: "dCoWsm",
    EXPLORE: "d4NYxq",
    LISTEN: "WPRwV",
};
