// -*- coding: utf-8 -*-
// Generated by scripts/generate_labels.py

export default {
    UPPER_SECONDARY: "dn4KHz",
    WORK_SKILLS: "dp73Sn",
    LOWER_PRIMARY: "by0beT",
    LOWER_SECONDARY: "svpsy",
    UPPER_PRIMARY: "bSQdiJ",
    PRESCHOOL: "b#GEd",
    BASIC_SKILLS: "chRJoI",
    PROFESSIONAL: "dnezU7",
    TERTIARY: "b&jDyf",
};
