// -*- coding: utf-8 -*-
// Generated by scripts/generate_labels.py

export default {
    UPPER_SECONDARY: "ZEjiwvOb",
    WORK_SKILLS: "Z#97dvst",
    LOWER_PRIMARY: "wnarlxKo",
    LOWER_SECONDARY: "eLt0Mbu4",
    UPPER_PRIMARY: "BkGYi3lD",
    PRESCHOOL: "FOhG0ib",
    BASIC_SKILLS: "H64ZOHfi",
    PROFESSIONAL: "ZrgBU73s",
    TERTIARY: "FYxwbxts",
};
