// -*- coding: utf-8 -*-
// Generated by scripts/generate_labels.py

export default {
    PEERS: "Ti5WR.cAsjNo",
    SPECIAL_SOFTWARE: "cfjB0R.mhgPB",
    OTHER_SUPPLIES: "cfjB0R.d4Uvx6",
    PAPER_PENCIL: "cfjB0R.cH#ig5",
    PEOPLE: "Ti5WR",
    MATERIALS: "cfjB0R",
    INTERNET: "cfjB0R.cdGFA5",
    TEACHER: "Ti5WR.ch#A9l",
};
