// -*- coding: utf-8 -*-
// Generated by scripts/generate_labels.py

export default {
    MEDIA: "bgStlE",
    TEXTBOOK: "cwRiL",
    LESSON_PLAN: "cHbILa",
    GAME: "d0o6Fw",
    BOOK: "dr5pZC",
    TUTORIAL: "dboes",
    ACTIVITY: "cpJLQx",
    LESSON: "bCz8L8",
    GUIDE: "dBtI2b",
    EXERCISE: "db5560",
};
