// -*- coding: utf-8 -*-
// Generated by scripts/generate_labels.py

export default {
    MEDIA: "rReY3LOO",
    TEXTBOOK: "LQYjqpA",
    LESSON_PLAN: "OqyPqhxW",
    GAME: "9dUN1LWT",
    BOOK: "0Et83gje",
    TUTORIAL: "WtHeUU1",
    ACTIVITY: "J45AL9Nb",
    LESSON: "xgFjFhrA",
    GUIDE: "204TGB4U",
    EXERCISE: "WEEETopZ",
};
