// -*- coding: utf-8 -*-
// Generated by scripts/generate_from_specs.py
// CompletionCriteria

export default {
    APPROX_TIME: "approx_time",
    MASTERY: "mastery",
    PAGES: "pages",
    REFERENCE: "reference",
    TIME: "time",
};

export const SCHEMA = {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "description": "Schema for completion criteria of content nodes",
  "additionalProperties": false,
  "definitions": {
    "model": {
      "type": "string",
      "$exportConstants": "completion_criteria",
      "enum": [
        "time",
        "approx_time",
        "pages",
        "mastery",
        "reference"
      ]
    },
    "mastery_criteria": {
      "type": "object",
      "$comment": "TODO move to separate schema",
      "additionalProperties": false,
      "required": ["mastery_model"],
      "properties": {
        "m": true,
        "n": true,
        "mastery_model": {
          "type": "string",
          "enum": [
            "do_all",
            "m_of_n",
            "num_correct_in_a_row_2",
            "num_correct_in_a_row_3",
            "num_correct_in_a_row_5",
            "num_correct_in_a_row_10"
          ]
        }
      },
      "anyOf": [
        {
          "properties": {
            "mastery_model": {
              "const": "m_of_n"
            }
          },
          "required": ["m", "n"]
        },
        {
          "properties": {
            "mastery_model": {
              "enum": [
                "do_all",
                "num_correct_in_a_row_2",
                "num_correct_in_a_row_3",
                "num_correct_in_a_row_5",
                "num_correct_in_a_row_10"
              ]
            },
            "m": {
              "type": "null"
            },
            "n": {
              "type": "null"
            }
          }
        }
      ]
    }
  },
  "properties": {
    "model": {
      "$ref": "#/definitions/model"
    },
    "learner_managed": {
      "type": "boolean"
    },
    "threshold": true
  },
  "required": ["model"],
  "anyOf": [
    {
      "properties": {
        "model": {
          "anyOf": [
            {"const": "time"},
            {"const": "approx_time"},
            {"const": "pages"}
          ]
        },
        "threshold": {
          "type": "number",
          "exclusiveMinimum": 0
        }
      },
      "required": ["threshold"]
    },
    {
      "properties": {
        "model": {
          "const": "mastery"
        },
        "threshold": {
          "$ref": "#/definitions/mastery_criteria"
        }
      },
      "required": ["threshold"]
    },
    {
      "properties": {
        "model": {
          "const": "reference"
        },
        "threshold": {
          "type": "null"
        }
      },
      "required": []
    }
  ]
};
