// -*- coding: utf-8 -*-
// Generated by scripts/generate_from_specs.py
// CompletionCriteria

export default {
    approx_time: "approx_time",
    mastery: "mastery",
    pages: "pages",
    reference: "reference",
    time: "time",
};
