// -*- coding: utf-8 -*-
// Generated by scripts/generate_labels.py

import Needs from "./labels/Needs";
import AccessibilityCategories from "./labels/AccessibilityCategories";
import ResourceType from "./labels/ResourceType";
import Levels from "./labels/Levels";
import Subjects from "./labels/Subjects";
import LearningActivities from "./labels/LearningActivities";

export default {
    Needs: Needs,
    AccessibilityCategories: AccessibilityCategories,
    ResourceType: ResourceType,
    Levels: Levels,
    Subjects: Subjects,
    LearningActivities: LearningActivities,
};
