// -*- coding: utf-8 -*-
// Generated by scripts/generate_labels.py

import AccessibilityCategories from "./labels/AccessibilityCategories";
import LearningActivities from "./labels/LearningActivities";
import Levels from "./labels/Levels";
import Needs from "./labels/Needs";
import ResourceType from "./labels/ResourceType";
import Subjects from "./labels/Subjects";

export default {
    AccessibilityCategories: AccessibilityCategories,
    LearningActivities: LearningActivities,
    Levels: Levels,
    Needs: Needs,
    ResourceType: ResourceType,
    Subjects: Subjects,
};
