// -*- coding: utf-8 -*-
// Generated by scripts/generate_from_specs.py
// Modalities

export default {
    COURSE: "COURSE",
    CUSTOM_NAVIGATION: "CUSTOM_NAVIGATION",
    LESSON: "LESSON",
    QUIZ: "QUIZ",
    SURVEY: "SURVEY",
    UNIT: "UNIT",
};
