# -*- coding: utf-8 -*-
# Generated by scripts/generate_from_specs.py
from __future__ import unicode_literals

# CompletionCriteria

APPROX_TIME = "approx_time"
MASTERY = "mastery"
PAGES = "pages"
REFERENCE = "reference"
TIME = "time"

choices = (
    (APPROX_TIME, "Approx Time"),
    (MASTERY, "Mastery"),
    (PAGES, "Pages"),
    (REFERENCE, "Reference"),
    (TIME, "Time"),
)

COMPLETIONCRITERIALIST = [
    APPROX_TIME,
    MASTERY,
    PAGES,
    REFERENCE,
    TIME,
]

SCHEMA = {
    "type": "object",
    "description": "Schema for completion criteria of content nodes",
    "additionalProperties": False,
    "definitions": {
        "model": {
            "type": "string",
            "$exportConstants": "completion_criteria",
            "enum": ["time", "approx_time", "pages", "mastery", "reference"],
        },
        "mastery_criteria": {
            "type": "object",
            "$comment": "TODO move to separate schema",
            "additionalProperties": False,
            "required": ["mastery_model"],
            "properties": {
                "m": True,
                "n": True,
                "mastery_model": {
                    "type": "string",
                    "enum": [
                        "do_all",
                        "m_of_n",
                        "num_correct_in_a_row_2",
                        "num_correct_in_a_row_3",
                        "num_correct_in_a_row_5",
                        "num_correct_in_a_row_10",
                    ],
                },
            },
            "anyOf": [
                {
                    "properties": {"mastery_model": {"const": "m_of_n"}},
                    "required": ["m", "n"],
                },
                {
                    "properties": {
                        "mastery_model": {
                            "enum": [
                                "do_all",
                                "num_correct_in_a_row_2",
                                "num_correct_in_a_row_3",
                                "num_correct_in_a_row_5",
                                "num_correct_in_a_row_10",
                            ]
                        },
                        "m": {"type": "null"},
                        "n": {"type": "null"},
                    }
                },
            ],
        },
    },
    "properties": {
        "model": {"$ref": "#/definitions/model"},
        "learner_managed": {"type": "boolean"},
        "threshold": True,
    },
    "required": ["model"],
    "anyOf": [
        {
            "properties": {
                "model": {
                    "anyOf": [
                        {"const": "time"},
                        {"const": "approx_time"},
                        {"const": "pages"},
                    ]
                },
                "threshold": {"type": "number", "exclusiveMinimum": 0},
            },
            "required": ["threshold"],
        },
        {
            "properties": {
                "model": {"const": "mastery"},
                "threshold": {"$ref": "#/definitions/mastery_criteria"},
            },
            "required": ["threshold"],
        },
        {
            "properties": {
                "model": {"const": "reference"},
                "threshold": {"type": "null"},
            },
            "required": [],
        },
    ],
}
