# -*- coding: utf-8 -*-
# Generated by scripts/generate_from_specs.py
from __future__ import unicode_literals

# CompletionCriteria

approx_time = "approx_time"
mastery = "mastery"
pages = "pages"
reference = "reference"
time = "time"

choices = (
    (approx_time, "Approx Time"),
    (mastery, "Mastery"),
    (pages, "Pages"),
    (reference, "Reference"),
    (time, "Time"),
)

COMPLETIONCRITERIALIST = [
    approx_time,
    mastery,
    pages,
    reference,
    time,
]
