# -*- coding: utf-8 -*-
# Generated by scripts/generate_from_specs.py
from __future__ import unicode_literals

# LearningObjectives


choices = ()

LEARNINGOBJECTIVESLIST = []

SCHEMA = {
    "$id": "/schemas/learning_objectives",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "description": "Schema for Learning Objectives mapping",
    "additionalProperties": False,
    "definitions": {
        "uuid": {
            "type": "string",
            "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[45][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$",
            "description": "A unique identifier in the form of a UUID v4 or v5",
        },
        "learning_objective_id": {
            "$ref": "#/definitions/uuid",
            "description": "Unique identifier for the Learning Objective",
        },
    },
    "properties": {
        "learning_objectives": {
            "type": "array",
            "description": "A list of Learning Objectives available in the unit",
            "minItems": 1,
            "items": {
                "type": "object",
                "properties": {
                    "id": {"$ref": "#/definitions/learning_objective_id"},
                    "text": {
                        "type": "string",
                        "minLength": 1,
                        "pattern": "^\\s*\\S[\\s\\S]*$",
                        "description": "Human-readable text describing the Learning Objective",
                    },
                    "metadata": {
                        "type": "object",
                        "description": "Optional metadata associated with the Learning Objective",
                    },
                },
                "required": ["id", "text"],
            },
        },
        "assessment_objectives": {
            "type": "object",
            "description": "Mapping of assessment question IDs to Learning Objective IDs",
            "minProperties": 1,
            "additionalProperties": False,
            "patternProperties": {
                "^[0-9a-f]{8}-[0-9a-f]{4}-[45][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$": {
                    "type": "array",
                    "items": {"$ref": "#/definitions/learning_objective_id"},
                }
            },
        },
        "lesson_objectives": {
            "type": "object",
            "description": "Mapping of lesson IDs to Learning Objective IDs",
            "minProperties": 1,
            "additionalProperties": False,
            "patternProperties": {
                "^[0-9a-f]{32}$": {
                    "type": "array",
                    "items": {"$ref": "#/definitions/learning_objective_id"},
                }
            },
        },
    },
    "required": ["learning_objectives", "assessment_objectives", "lesson_objectives"],
}
