# -*- coding: utf-8 -*-
# Generated by scripts/generate_from_specs.py
from __future__ import unicode_literals

# Library

COMMUNITY = "COMMUNITY"
KOLIBRI = "KOLIBRI"

choices = (
    (COMMUNITY, "Community"),
    (KOLIBRI, "Kolibri"),
)

LIBRARYLIST = [
    COMMUNITY,
    KOLIBRI,
]
