# -*- coding: utf-8 -*-
# Generated by scripts/generate_from_specs.py
from __future__ import unicode_literals

# Modalities

CUSTOM_NAVIGATION = "CUSTOM_NAVIGATION"
QUIZ = "QUIZ"

choices = (
    (CUSTOM_NAVIGATION, "Custom Navigation"),
    (QUIZ, "Quiz"),
)

MODALITIESLIST = [
    CUSTOM_NAVIGATION,
    QUIZ,
]
