# -*- coding: utf-8 -*-
# Generated by scripts/generate_from_specs.py
from __future__ import unicode_literals

# Uuid

KOLIBRI_ECOSYSTEM_UUID_NAMESPACE = "237627f4-3601-11ee-a67c-595de72bede7"

choices = ((KOLIBRI_ECOSYSTEM_UUID_NAMESPACE, "Kolibri Ecosystem Uuid Namespace"),)

UUIDLIST = [
    KOLIBRI_ECOSYSTEM_UUID_NAMESPACE,
]
