# -*- coding: utf-8 -*-
# Generated by scripts/generate_labels.py
from __future__ import unicode_literals

# AccessibilityCategories

AUDIO_DESCRIPTION = "cwDcsY"
ALT_TEXT = "cuhrmh"
CAPTIONS_SUBTITLES = "da2iCe"
HIGH_CONTRAST = "br&HYl"
TAGGED_PDF = "crDF4W"
SIGN_LANGUAGE = "b1hGk&"

choices = (
    (AUDIO_DESCRIPTION, "Audio Description"),
    (ALT_TEXT, "Alt Text"),
    (CAPTIONS_SUBTITLES, "Captions Subtitles"),
    (HIGH_CONTRAST, "High Contrast"),
    (TAGGED_PDF, "Tagged Pdf"),
    (SIGN_LANGUAGE, "Sign Language"),
)

ACCESSIBILITYCATEGORIESLIST = [
    AUDIO_DESCRIPTION,
    ALT_TEXT,
    CAPTIONS_SUBTITLES,
    HIGH_CONTRAST,
    TAGGED_PDF,
    SIGN_LANGUAGE,
]
