# -*- coding: utf-8 -*-
# Generated by scripts/generate_labels.py
from __future__ import unicode_literals

# AccessibilityCategories

AUDIO_DESCRIPTION = "LNqKSN9j"
ALT_TEXT = "Lb0tb9VC"
CAPTIONS_SUBTITLES = "WnIhbgkY"
HIGH_CONTRAST = "uF4CI2wP"
TAGGED_PDF = "Kxx#meDW"
SIGN_LANGUAGE = "Dr4cVXkc"

choices = (
    (AUDIO_DESCRIPTION, "Audio Description"),
    (ALT_TEXT, "Alt Text"),
    (CAPTIONS_SUBTITLES, "Captions Subtitles"),
    (HIGH_CONTRAST, "High Contrast"),
    (TAGGED_PDF, "Tagged Pdf"),
    (SIGN_LANGUAGE, "Sign Language"),
)

ACCESSIBILITYCATEGORIESLIST = [
    AUDIO_DESCRIPTION,
    ALT_TEXT,
    CAPTIONS_SUBTITLES,
    HIGH_CONTRAST,
    TAGGED_PDF,
    SIGN_LANGUAGE,
]
