# -*- coding: utf-8 -*-
# Generated by scripts/generate_from_specs.py
from __future__ import unicode_literals

# AccessibilityCategories

ALT_TEXT = "Lb0tb9VC"
AUDIO_DESCRIPTION = "LNqKSN9j"
CAPTIONS_SUBTITLES = "WnIhbgkY"
HIGH_CONTRAST = "uF4CI2wP"
SIGN_LANGUAGE = "Dr4cVXkc"
TAGGED_PDF = "Kxx#meDW"

choices = (
    (ALT_TEXT, "Alt Text"),
    (AUDIO_DESCRIPTION, "Audio Description"),
    (CAPTIONS_SUBTITLES, "Captions Subtitles"),
    (HIGH_CONTRAST, "High Contrast"),
    (SIGN_LANGUAGE, "Sign Language"),
    (TAGGED_PDF, "Tagged Pdf"),
)

ACCESSIBILITYCATEGORIESLIST = [
    ALT_TEXT,
    AUDIO_DESCRIPTION,
    CAPTIONS_SUBTITLES,
    HIGH_CONTRAST,
    SIGN_LANGUAGE,
    TAGGED_PDF,
]
