# -*- coding: utf-8 -*-
# Generated by scripts/generate_labels.py
from __future__ import unicode_literals

# LearningActivities

READ = "bzRtvr"
CREATE = "c7fP3a"
PRACTICE = "c9ATW4"
WATCH = "c53M6c"
REFLECT = "dCoWsm"
EXPLORE = "d4NYxq"
LISTEN = "WPRwV"

choices = (
    (READ, "Read"),
    (CREATE, "Create"),
    (PRACTICE, "Practice"),
    (WATCH, "Watch"),
    (REFLECT, "Reflect"),
    (EXPLORE, "Explore"),
    (LISTEN, "Listen"),
)

LEARNINGACTIVITIESLIST = [
    READ,
    CREATE,
    PRACTICE,
    WATCH,
    REFLECT,
    EXPLORE,
    LISTEN,
]
