# -*- coding: utf-8 -*-
# Generated by scripts/generate_from_specs.py
from __future__ import unicode_literals

# LearningActivities

CREATE = "UXADWcXZ"
EXPLORE = "#j8L0eq3"
LISTEN = "mkA1R3NU"
PRACTICE = "VwRCom7G"
READ = "wA01urpi"
REFLECT = "3dSeJhqs"
WATCH = "UD5UGM0z"

choices = (
    (CREATE, "Create"),
    (EXPLORE, "Explore"),
    (LISTEN, "Listen"),
    (PRACTICE, "Practice"),
    (READ, "Read"),
    (REFLECT, "Reflect"),
    (WATCH, "Watch"),
)

LEARNINGACTIVITIESLIST = [
    CREATE,
    EXPLORE,
    LISTEN,
    PRACTICE,
    READ,
    REFLECT,
    WATCH,
]
