# -*- coding: utf-8 -*-
# Generated by scripts/generate_labels.py
from __future__ import unicode_literals

# LearningActivities

READ = "wA01urpi"
CREATE = "UXADWcXZ"
PRACTICE = "VwRCom7G"
WATCH = "UD5UGM0z"
REFLECT = "3dSeJhqs"
EXPLORE = "#j8L0eq3"
LISTEN = "mkA1R3NU"

choices = (
    (READ, "Read"),
    (CREATE, "Create"),
    (PRACTICE, "Practice"),
    (WATCH, "Watch"),
    (REFLECT, "Reflect"),
    (EXPLORE, "Explore"),
    (LISTEN, "Listen"),
)

LEARNINGACTIVITIESLIST = [
    READ,
    CREATE,
    PRACTICE,
    WATCH,
    REFLECT,
    EXPLORE,
    LISTEN,
]
