# -*- coding: utf-8 -*-
# Generated by scripts/generate_labels.py
from __future__ import unicode_literals

# Levels

UPPER_SECONDARY = "dn4KHz"
WORK_SKILLS = "dp73Sn"
LOWER_PRIMARY = "by0beT"
LOWER_SECONDARY = "svpsy"
UPPER_PRIMARY = "bSQdiJ"
PRESCHOOL = "b#GEd"
BASIC_SKILLS = "chRJoI"
PROFESSIONAL = "dnezU7"
TERTIARY = "b&jDyf"

choices = (
    (UPPER_SECONDARY, "Upper Secondary"),
    (WORK_SKILLS, "Work Skills"),
    (LOWER_PRIMARY, "Lower Primary"),
    (LOWER_SECONDARY, "Lower Secondary"),
    (UPPER_PRIMARY, "Upper Primary"),
    (PRESCHOOL, "Preschool"),
    (BASIC_SKILLS, "Basic Skills"),
    (PROFESSIONAL, "Professional"),
    (TERTIARY, "Tertiary"),
)

LEVELSLIST = [
    UPPER_SECONDARY,
    WORK_SKILLS,
    LOWER_PRIMARY,
    LOWER_SECONDARY,
    UPPER_PRIMARY,
    PRESCHOOL,
    BASIC_SKILLS,
    PROFESSIONAL,
    TERTIARY,
]
