# -*- coding: utf-8 -*-
# Generated by scripts/generate_labels.py
from __future__ import unicode_literals

# Needs

PEERS = "Ti5WR.cAsjNo"
SPECIAL_SOFTWARE = "cfjB0R.mhgPB"
OTHER_SUPPLIES = "cfjB0R.d4Uvx6"
PAPER_PENCIL = "cfjB0R.cH#ig5"
PEOPLE = "Ti5WR"
MATERIALS = "cfjB0R"
INTERNET = "cfjB0R.cdGFA5"
TEACHER = "Ti5WR.ch#A9l"

choices = (
    (PEERS, "Peers"),
    (SPECIAL_SOFTWARE, "Special Software"),
    (OTHER_SUPPLIES, "Other Supplies"),
    (PAPER_PENCIL, "Paper Pencil"),
    (PEOPLE, "People"),
    (MATERIALS, "Materials"),
    (INTERNET, "Internet"),
    (TEACHER, "Teacher"),
)

NEEDSLIST = [
    PEERS,
    SPECIAL_SOFTWARE,
    OTHER_SUPPLIES,
    PAPER_PENCIL,
    PEOPLE,
    MATERIALS,
    INTERNET,
    TEACHER,
]
