# -*- coding: utf-8 -*-
# Generated by scripts/generate_labels.py
from __future__ import unicode_literals

# Needs

PRIOR_KNOWLEDGE = "biiiAR"
MATERIALS = "cfjB0R"
FOR_BEGINNERS = "biiiAR.bjQPib"
PAPER_PENCIL = "cfjB0R.cH#ig5"
OTHER_SUPPLIES = "cfjB0R.d4Uvx6"
INTERNET = "cfjB0R.cdGFA5"
SPECIAL_SOFTWARE = "cfjB0R.mhgPB"
PEOPLE = "Ti5WR"
PEERS = "Ti5WR.cAsjNo"
TEACHER = "Ti5WR.ch#A9l"

choices = (
    (PRIOR_KNOWLEDGE, "Prior Knowledge"),
    (MATERIALS, "Materials"),
    (FOR_BEGINNERS, "For Beginners"),
    (PAPER_PENCIL, "Paper Pencil"),
    (OTHER_SUPPLIES, "Other Supplies"),
    (INTERNET, "Internet"),
    (SPECIAL_SOFTWARE, "Special Software"),
    (PEOPLE, "People"),
    (PEERS, "Peers"),
    (TEACHER, "Teacher"),
)

NEEDSLIST = [
    PRIOR_KNOWLEDGE,
    MATERIALS,
    FOR_BEGINNERS,
    PAPER_PENCIL,
    OTHER_SUPPLIES,
    INTERNET,
    SPECIAL_SOFTWARE,
    PEOPLE,
    PEERS,
    TEACHER,
]
