# -*- coding: utf-8 -*-
# Generated by scripts/generate_labels.py
from __future__ import unicode_literals

# ResourceType

MEDIA = "bgStlE"
TEXTBOOK = "cwRiL"
LESSON_PLAN = "cHbILa"
GAME = "d0o6Fw"
BOOK = "dr5pZC"
TUTORIAL = "dboes"
ACTIVITY = "cpJLQx"
LESSON = "bCz8L8"
GUIDE = "dBtI2b"
EXERCISE = "db5560"

choices = (
    (MEDIA, "Media"),
    (TEXTBOOK, "Textbook"),
    (LESSON_PLAN, "Lesson Plan"),
    (GAME, "Game"),
    (BOOK, "Book"),
    (TUTORIAL, "Tutorial"),
    (ACTIVITY, "Activity"),
    (LESSON, "Lesson"),
    (GUIDE, "Guide"),
    (EXERCISE, "Exercise"),
)

RESOURCETYPELIST = [
    MEDIA,
    TEXTBOOK,
    LESSON_PLAN,
    GAME,
    BOOK,
    TUTORIAL,
    ACTIVITY,
    LESSON,
    GUIDE,
    EXERCISE,
]
