# -*- coding: utf-8 -*-
# Generated by scripts/generate_labels.py
from __future__ import unicode_literals

# ResourceType

MEDIA = "rReY3LOO"
TEXTBOOK = "LQYjqpA"
LESSON_PLAN = "OqyPqhxW"
GAME = "9dUN1LWT"
BOOK = "0Et83gje"
TUTORIAL = "WtHeUU1"
ACTIVITY = "J45AL9Nb"
LESSON = "xgFjFhrA"
GUIDE = "204TGB4U"
EXERCISE = "WEEETopZ"

choices = (
    (MEDIA, "Media"),
    (TEXTBOOK, "Textbook"),
    (LESSON_PLAN, "Lesson Plan"),
    (GAME, "Game"),
    (BOOK, "Book"),
    (TUTORIAL, "Tutorial"),
    (ACTIVITY, "Activity"),
    (LESSON, "Lesson"),
    (GUIDE, "Guide"),
    (EXERCISE, "Exercise"),
)

RESOURCETYPELIST = [
    MEDIA,
    TEXTBOOK,
    LESSON_PLAN,
    GAME,
    BOOK,
    TUTORIAL,
    ACTIVITY,
    LESSON,
    GUIDE,
    EXERCISE,
]
