# -*- coding: utf-8 -*-
# Generated by scripts/generate_from_specs.py
from __future__ import unicode_literals

# ResourceType

ACTIVITY = "J45AL9Nb"
BOOK = "0Et83gje"
EXERCISE = "WEEETopZ"
GAME = "9dUN1LWT"
GUIDE = "204TGB4U"
LESSON = "xgFjFhrA"
LESSON_PLAN = "OqyPqhxW"
MEDIA = "rReY3LOO"
TEXTBOOK = "LQYjqpA"
TUTORIAL = "WtHeUU1"

choices = (
    (ACTIVITY, "Activity"),
    (BOOK, "Book"),
    (EXERCISE, "Exercise"),
    (GAME, "Game"),
    (GUIDE, "Guide"),
    (LESSON, "Lesson"),
    (LESSON_PLAN, "Lesson Plan"),
    (MEDIA, "Media"),
    (TEXTBOOK, "Textbook"),
    (TUTORIAL, "Tutorial"),
)

RESOURCETYPELIST = [
    ACTIVITY,
    BOOK,
    EXERCISE,
    GAME,
    GUIDE,
    LESSON,
    LESSON_PLAN,
    MEDIA,
    TEXTBOOK,
    TUTORIAL,
]
