# -*- coding: utf-8 -*-
# Generated by scripts/generate_labels.py
from __future__ import unicode_literals

# Subjects

LOGIC_AND_CRITICAL_THINKING = "nX2&DRtz.YMBXStib"
CALCULUS = "d&WXdXWF.qs0Xlaxq.8rJ57ht6"
NUMERACY = "nX2&DRtz.Tsyej9ta"
READING_COMPREHENSION = "d&WXdXWF.kHKJ&PbV.r7RxB#9t"
TECHNICAL_AND_VOCATIONAL_TRAINING = "l7DsPDlm.ISEXeZt&"
LEARNING_SKILLS = "nX2&DRtz.fP2j70bj"
PROGRAMMING = "d&WXdXWF.e#RTW9E#.CfnlTDZ#"
WRITING = "d&WXdXWF.kHKJ&PbV.KFJOCr&6"
ANTHROPOLOGY = "d&WXdXWF.K80UMYnW.ViBlbQR&"
LESSON_PLANS = "ziJ6PCuU.lOBPr5ix"
SOCIAL_SCIENCES = "d&WXdXWF.K80UMYnW"
LITERATURE = "d&WXdXWF.kHKJ&PbV.DJLBbaEk"
MATHEMATICS = "d&WXdXWF.qs0Xlaxq"
DAILY_LIFE = "PbGoe2MV"
CHEMISTRY = "d&WXdXWF.i1IdaNwr.#r5ocgid"
PHYSICS = "d&WXdXWF.i1IdaNwr.r#wbt#jF"
FOR_TEACHERS = "ziJ6PCuU"
ARTS = "d&WXdXWF.5QAjgfv7"
MENTAL_HEALTH = "PbGoe2MV.d8&gCo2N"
DANCE = "d&WXdXWF.5QAjgfv7.BUMJJBnS"
WORK = "l7DsPDlm"
SCIENCES = "d&WXdXWF.i1IdaNwr"
CIVIC_EDUCATION = "d&WXdXWF.K80UMYnW.F863vKiF"
TOOLS_AND_SOFTWARE_TRAINING = "l7DsPDlm.ISEXeZt&.1JfIbP&N"
ASTRONOMY = "d&WXdXWF.i1IdaNwr.mjSF4QlF"
EARTH_SCIENCE = "d&WXdXWF.i1IdaNwr.zbDzxDE7"
COMPUTER_SCIENCE = "d&WXdXWF.e#RTW9E#"
SOCIOLOGY = "d&WXdXWF.K80UMYnW.75WBu1ZS"
CURRENT_EVENTS = "PbGoe2MV.J7CU1IxN"
BIOLOGY = "d&WXdXWF.i1IdaNwr.uErN4PdS"
POLITICAL_SCIENCE = "d&WXdXWF.K80UMYnW.K72&pITr"
DRAMA = "d&WXdXWF.5QAjgfv7.XsWznP4o"
MUSIC = "d&WXdXWF.5QAjgfv7.u0aKjT4i"
MECHANICAL_ENGINEERING = "d&WXdXWF.e#RTW9E#.8ZoaPsVW"
DIGITAL_LITERACY = "nX2&DRtz.wZ3EAedB"
WEB_DESIGN = "d&WXdXWF.e#RTW9E#.P7s8FxQ8"
LITERACY = "nX2&DRtz.HLo9TbNq"
ENTREPRENEURSHIP = "PbGoe2MV.kyxTNsRS"
GUIDES = "ziJ6PCuU.RLfhp37t"
HISTORY = "d&WXdXWF.zWtcJ&F2"
VISUAL_ART = "d&WXdXWF.5QAjgfv7.4LskOFXj"
ENVIRONMENT = "PbGoe2MV.tS7WKnZ7"
SCHOOL = "d&WXdXWF"
STATISTICS = "d&WXdXWF.qs0Xlaxq.jNm15RLB"
SKILLS_TRAINING = "l7DsPDlm.ISEXeZt&.&1WpYE&n"
ALGEBRA = "d&WXdXWF.qs0Xlaxq.0t5msbL5"
GEOMETRY = "d&WXdXWF.qs0Xlaxq.lb7ELcK5"
DIVERSITY = "PbGoe2MV.EHcbjuKq"
FINANCIAL_LITERACY = "PbGoe2MV.HGIc9sZq"
PUBLIC_HEALTH = "PbGoe2MV.kivAZaeX"
INDUSTRY_AND_SECTOR_SPECIFIC = "l7DsPDlm.ISEXeZt&.pRvOzJTE"
MEDIA_LITERACY = "PbGoe2MV.UOTL#KIV"
READING_AND_WRITING = "d&WXdXWF.kHKJ&PbV"
LANGUAGE_LEARNING = "d&WXdXWF.JDUfJNXc"
BASIC_SKILLS = "nX2&DRtz"
PROFESSIONAL_SKILLS = "l7DsPDlm.#N2VymZo"
ARITHMETIC = "d&WXdXWF.qs0Xlaxq.nG96nHDc"

choices = (
    (LOGIC_AND_CRITICAL_THINKING, "Logic And Critical Thinking"),
    (CALCULUS, "Calculus"),
    (NUMERACY, "Numeracy"),
    (READING_COMPREHENSION, "Reading Comprehension"),
    (TECHNICAL_AND_VOCATIONAL_TRAINING, "Technical And Vocational Training"),
    (LEARNING_SKILLS, "Learning Skills"),
    (PROGRAMMING, "Programming"),
    (WRITING, "Writing"),
    (ANTHROPOLOGY, "Anthropology"),
    (LESSON_PLANS, "Lesson Plans"),
    (SOCIAL_SCIENCES, "Social Sciences"),
    (LITERATURE, "Literature"),
    (MATHEMATICS, "Mathematics"),
    (DAILY_LIFE, "Daily Life"),
    (CHEMISTRY, "Chemistry"),
    (PHYSICS, "Physics"),
    (FOR_TEACHERS, "For Teachers"),
    (ARTS, "Arts"),
    (MENTAL_HEALTH, "Mental Health"),
    (DANCE, "Dance"),
    (WORK, "Work"),
    (SCIENCES, "Sciences"),
    (CIVIC_EDUCATION, "Civic Education"),
    (TOOLS_AND_SOFTWARE_TRAINING, "Tools And Software Training"),
    (ASTRONOMY, "Astronomy"),
    (EARTH_SCIENCE, "Earth Science"),
    (COMPUTER_SCIENCE, "Computer Science"),
    (SOCIOLOGY, "Sociology"),
    (CURRENT_EVENTS, "Current Events"),
    (BIOLOGY, "Biology"),
    (POLITICAL_SCIENCE, "Political Science"),
    (DRAMA, "Drama"),
    (MUSIC, "Music"),
    (MECHANICAL_ENGINEERING, "Mechanical Engineering"),
    (DIGITAL_LITERACY, "Digital Literacy"),
    (WEB_DESIGN, "Web Design"),
    (LITERACY, "Literacy"),
    (ENTREPRENEURSHIP, "Entrepreneurship"),
    (GUIDES, "Guides"),
    (HISTORY, "History"),
    (VISUAL_ART, "Visual Art"),
    (ENVIRONMENT, "Environment"),
    (SCHOOL, "School"),
    (STATISTICS, "Statistics"),
    (SKILLS_TRAINING, "Skills Training"),
    (ALGEBRA, "Algebra"),
    (GEOMETRY, "Geometry"),
    (DIVERSITY, "Diversity"),
    (FINANCIAL_LITERACY, "Financial Literacy"),
    (PUBLIC_HEALTH, "Public Health"),
    (INDUSTRY_AND_SECTOR_SPECIFIC, "Industry And Sector Specific"),
    (MEDIA_LITERACY, "Media Literacy"),
    (READING_AND_WRITING, "Reading And Writing"),
    (LANGUAGE_LEARNING, "Language Learning"),
    (BASIC_SKILLS, "Basic Skills"),
    (PROFESSIONAL_SKILLS, "Professional Skills"),
    (ARITHMETIC, "Arithmetic"),
)

SUBJECTSLIST = [
    LOGIC_AND_CRITICAL_THINKING,
    CALCULUS,
    NUMERACY,
    READING_COMPREHENSION,
    TECHNICAL_AND_VOCATIONAL_TRAINING,
    LEARNING_SKILLS,
    PROGRAMMING,
    WRITING,
    ANTHROPOLOGY,
    LESSON_PLANS,
    SOCIAL_SCIENCES,
    LITERATURE,
    MATHEMATICS,
    DAILY_LIFE,
    CHEMISTRY,
    PHYSICS,
    FOR_TEACHERS,
    ARTS,
    MENTAL_HEALTH,
    DANCE,
    WORK,
    SCIENCES,
    CIVIC_EDUCATION,
    TOOLS_AND_SOFTWARE_TRAINING,
    ASTRONOMY,
    EARTH_SCIENCE,
    COMPUTER_SCIENCE,
    SOCIOLOGY,
    CURRENT_EVENTS,
    BIOLOGY,
    POLITICAL_SCIENCE,
    DRAMA,
    MUSIC,
    MECHANICAL_ENGINEERING,
    DIGITAL_LITERACY,
    WEB_DESIGN,
    LITERACY,
    ENTREPRENEURSHIP,
    GUIDES,
    HISTORY,
    VISUAL_ART,
    ENVIRONMENT,
    SCHOOL,
    STATISTICS,
    SKILLS_TRAINING,
    ALGEBRA,
    GEOMETRY,
    DIVERSITY,
    FINANCIAL_LITERACY,
    PUBLIC_HEALTH,
    INDUSTRY_AND_SECTOR_SPECIFIC,
    MEDIA_LITERACY,
    READING_AND_WRITING,
    LANGUAGE_LEARNING,
    BASIC_SKILLS,
    PROFESSIONAL_SKILLS,
    ARITHMETIC,
]
