# -*- coding: utf-8 -*-
# Generated by scripts/generate_labels.py
from __future__ import unicode_literals

# Subjects

LOGIC_AND_CRITICAL_THINKING = "3hB92.dkzVgX"
CALCULUS = "p&dep.bblteS.dXgpNS"
NUMERACY = "3hB92.c1jGqN"
READING_COMPREHENSION = "p&dep.Qgsp#.bhUTDV"
TECHNICAL_AND_VOCATIONAL_TRAINING = "VT1kL.ckX7et"
LEARNING_SKILLS = "3hB92.wNyNV"
PROGRAMMING = "p&dep.t6U3d.bWu0U1"
WRITING = "p&dep.Qgsp#.cr#oHX"
ANTHROPOLOGY = "p&dep.ctZs6B.c8HSSg"
LESSON_PLANS = "bKIpQL.UHULh"
SOCIAL_SCIENCES = "p&dep.ctZs6B"
LITERATURE = "p&dep.Qgsp#.b2ovSe"
MATHEMATICS = "p&dep.bblteS"
DAILY_LIFE = "cKga4t"
CHEMISTRY = "p&dep.Jwimc.d5hK4i"
PHYSICS = "p&dep.Jwimc.bh5yfp"
FOR_TEACHERS = "bKIpQL"
ARTS = "p&dep.dMPOKy"
MENTAL_HEALTH = "cKga4t.pZ8zW"
DANCE = "p&dep.dMPOKy.bU6Aon"
WORK = "VT1kL"
SCIENCES = "p&dep.Jwimc"
CIVIC_EDUCATION = "p&dep.ctZs6B.b&ZRDw"
TOOLS_AND_SOFTWARE_TRAINING = "VT1kL.ckX7et.dwmwig"
ASTRONOMY = "p&dep.Jwimc.WMX&I"
EARTH_SCIENCE = "p&dep.Jwimc.bKf1LD"
COMPUTER_SCIENCE = "p&dep.t6U3d"
SOCIOLOGY = "p&dep.ctZs6B.dVNbTt"
CURRENT_EVENTS = "cKga4t.cpTY7w"
BIOLOGY = "p&dep.Jwimc.br5gFI"
POLITICAL_SCIENCE = "p&dep.ctZs6B.ctVB8#"
DRAMA = "p&dep.dMPOKy.dflbK2"
MUSIC = "p&dep.dMPOKy.btqcqM"
MECHANICAL_ENGINEERING = "p&dep.t6U3d.dZm4cL"
DIGITAL_LITERACY = "3hB92.bBpD5O"
WEB_DESIGN = "p&dep.t6U3d.cNTlX9"
LITERACY = "3hB92.cgu720"
ENTREPRENEURSHIP = "cKga4t.PHE2D"
GUIDES = "bKIpQL.cUuuC&"
HISTORY = "p&dep.bNbmkp"
VISUAL_ART = "p&dep.dMPOKy.dIviQH"
ENVIRONMENT = "cKga4t.boZVcq"
SCHOOL = "p&dep"
STATISTICS = "p&dep.bblteS.MCZxM"
SKILLS_TRAINING = "VT1kL.ckX7et.d&xa&j"
ALGEBRA = "p&dep.bblteS.drpKXi"
GEOMETRY = "p&dep.bblteS.ShT6u"
DIVERSITY = "cKga4t.b6eieL"
FINANCIAL_LITERACY = "cKga4t.cgcil1"
PUBLIC_HEALTH = "cKga4t.OHvRm"
INDUSTRY_AND_SECTOR_SPECIFIC = "VT1kL.ckX7et.#TwHM"
MEDIA_LITERACY = "cKga4t.c6I2x6"
READING_AND_WRITING = "p&dep.Qgsp#"
LANGUAGE_LEARNING = "p&dep.cn24wo"
BASIC_SKILLS = "3hB92"
PROFESSIONAL_SKILLS = "VT1kL.d6FA9G"
ARITHMETIC = "p&dep.bblteS.2d3O2"

choices = (
    (LOGIC_AND_CRITICAL_THINKING, "Logic And Critical Thinking"),
    (CALCULUS, "Calculus"),
    (NUMERACY, "Numeracy"),
    (READING_COMPREHENSION, "Reading Comprehension"),
    (TECHNICAL_AND_VOCATIONAL_TRAINING, "Technical And Vocational Training"),
    (LEARNING_SKILLS, "Learning Skills"),
    (PROGRAMMING, "Programming"),
    (WRITING, "Writing"),
    (ANTHROPOLOGY, "Anthropology"),
    (LESSON_PLANS, "Lesson Plans"),
    (SOCIAL_SCIENCES, "Social Sciences"),
    (LITERATURE, "Literature"),
    (MATHEMATICS, "Mathematics"),
    (DAILY_LIFE, "Daily Life"),
    (CHEMISTRY, "Chemistry"),
    (PHYSICS, "Physics"),
    (FOR_TEACHERS, "For Teachers"),
    (ARTS, "Arts"),
    (MENTAL_HEALTH, "Mental Health"),
    (DANCE, "Dance"),
    (WORK, "Work"),
    (SCIENCES, "Sciences"),
    (CIVIC_EDUCATION, "Civic Education"),
    (TOOLS_AND_SOFTWARE_TRAINING, "Tools And Software Training"),
    (ASTRONOMY, "Astronomy"),
    (EARTH_SCIENCE, "Earth Science"),
    (COMPUTER_SCIENCE, "Computer Science"),
    (SOCIOLOGY, "Sociology"),
    (CURRENT_EVENTS, "Current Events"),
    (BIOLOGY, "Biology"),
    (POLITICAL_SCIENCE, "Political Science"),
    (DRAMA, "Drama"),
    (MUSIC, "Music"),
    (MECHANICAL_ENGINEERING, "Mechanical Engineering"),
    (DIGITAL_LITERACY, "Digital Literacy"),
    (WEB_DESIGN, "Web Design"),
    (LITERACY, "Literacy"),
    (ENTREPRENEURSHIP, "Entrepreneurship"),
    (GUIDES, "Guides"),
    (HISTORY, "History"),
    (VISUAL_ART, "Visual Art"),
    (ENVIRONMENT, "Environment"),
    (SCHOOL, "School"),
    (STATISTICS, "Statistics"),
    (SKILLS_TRAINING, "Skills Training"),
    (ALGEBRA, "Algebra"),
    (GEOMETRY, "Geometry"),
    (DIVERSITY, "Diversity"),
    (FINANCIAL_LITERACY, "Financial Literacy"),
    (PUBLIC_HEALTH, "Public Health"),
    (INDUSTRY_AND_SECTOR_SPECIFIC, "Industry And Sector Specific"),
    (MEDIA_LITERACY, "Media Literacy"),
    (READING_AND_WRITING, "Reading And Writing"),
    (LANGUAGE_LEARNING, "Language Learning"),
    (BASIC_SKILLS, "Basic Skills"),
    (PROFESSIONAL_SKILLS, "Professional Skills"),
    (ARITHMETIC, "Arithmetic"),
)

SUBJECTSLIST = [
    LOGIC_AND_CRITICAL_THINKING,
    CALCULUS,
    NUMERACY,
    READING_COMPREHENSION,
    TECHNICAL_AND_VOCATIONAL_TRAINING,
    LEARNING_SKILLS,
    PROGRAMMING,
    WRITING,
    ANTHROPOLOGY,
    LESSON_PLANS,
    SOCIAL_SCIENCES,
    LITERATURE,
    MATHEMATICS,
    DAILY_LIFE,
    CHEMISTRY,
    PHYSICS,
    FOR_TEACHERS,
    ARTS,
    MENTAL_HEALTH,
    DANCE,
    WORK,
    SCIENCES,
    CIVIC_EDUCATION,
    TOOLS_AND_SOFTWARE_TRAINING,
    ASTRONOMY,
    EARTH_SCIENCE,
    COMPUTER_SCIENCE,
    SOCIOLOGY,
    CURRENT_EVENTS,
    BIOLOGY,
    POLITICAL_SCIENCE,
    DRAMA,
    MUSIC,
    MECHANICAL_ENGINEERING,
    DIGITAL_LITERACY,
    WEB_DESIGN,
    LITERACY,
    ENTREPRENEURSHIP,
    GUIDES,
    HISTORY,
    VISUAL_ART,
    ENVIRONMENT,
    SCHOOL,
    STATISTICS,
    SKILLS_TRAINING,
    ALGEBRA,
    GEOMETRY,
    DIVERSITY,
    FINANCIAL_LITERACY,
    PUBLIC_HEALTH,
    INDUSTRY_AND_SECTOR_SPECIFIC,
    MEDIA_LITERACY,
    READING_AND_WRITING,
    LANGUAGE_LEARNING,
    BASIC_SKILLS,
    PROFESSIONAL_SKILLS,
    ARITHMETIC,
]
