name: Finalized specs

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  change_check:
    name: Check if file changed
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      modified: ${{ steps.changes.outputs.modified }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - id: changes
        # Set outputs using the command.
        run: |
          echo "modified=$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep spec/labels-v1.json$ | xargs)" >> $GITHUB_OUTPUT
  unit_test:
    name: Error if finalized spec modified
    needs: change_check
    if: ${{ needs.change_check.outputs.modified }}
    runs-on: ubuntu-latest
    steps:
    - name: Fail if specs modified
      run: exit 1
